[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Stage,
    [string]$Config,
    [switch]$PreflightOnly, [switch]$SmokeTest, [switch]$FreshStart, [switch]$Resume,
    [string]$ProjectRoot = "F:\AI\TrustCXR"
)
$routes = @{
    "9B" = "scripts\training\run_stage9b_external.ps1"
    "9C" = "scripts\evaluation\run_stage9c_comparison.ps1"
    "9_FINAL" = "scripts\evaluation\run_stage9_final_evaluation.ps1"
    "10A" = "scripts\localization\run_stage10a_annotation_audit.ps1"
    "10B" = "scripts\localization\run_stage10b_governance_identity.ps1"
    "10C" = "scripts\localization\run_stage10c_governance_adjudication.ps1"
    "10D" = "scripts\localization\run_stage10d_rsna_patient_split.ps1"
    "10E" = "scripts\localization\run_stage10e_rsna_localization.ps1"
    "10F" = "scripts\localization\run_stage10f_validation_audit.ps1"
    "10G" = "scripts\localization\run_stage10g_validation_failure_analysis.ps1"
    "10H" = "scripts\localization\run_stage10h_operating_point_audit.ps1"
    "10I" = "scripts\localization\run_stage10i_operating_point_decision.ps1"
    "10J" = "scripts\localization\run_stage10j_small_lesion_repair.ps1"
    "10K" = "scripts\localization\run_stage10k_paired_failure_analysis.ps1"
    "10L" = "scripts\localization\run_stage10l_baseline_selection_freeze.ps1"
    "10M" = "scripts\localization\run_stage10m_validation_anatomical_audit.ps1"
    "10N" = "scripts\localization\run_stage10n_localization_acceptance_decision.ps1"
    "11A" = "scripts\fusion\run_stage11a_evidence_fusion_contract.ps1"
    "11B" = "scripts\fusion\run_stage11b_fusion_data_contract_validation.ps1"
    "11C" = "scripts\fusion\run_stage11c_shared_cohort_label_harmonization.ps1"
    "11D" = "scripts\fusion\run_stage11d_official_identity_mapping_audit.ps1"
    "11E" = "scripts\fusion\run_stage11e_shared_cohort_split_repair.ps1"
    "11F" = "scripts\fusion\run_stage11f_shared_cohort_fusion_validation.ps1"
    "11G" = "scripts\fusion\run_stage11g_fusion_implementation.ps1"
    "11H" = "scripts\fusion\run_stage11h_record_level_fusion_evaluation.ps1"
    "11I" = "scripts\fusion\run_stage11i_fusion_coverage_decision.ps1"
    "11J" = "scripts\fusion\run_stage11j_shared_validation_prediction_coverage.ps1"
    "11K" = "scripts\fusion\run_stage11k_complete_coverage_fusion_evaluation.ps1"
    "11L" = "scripts\fusion\run_stage11l_fusion_acceptance_decision.ps1"
    "12A" = "scripts\quality\run_stage12a_quality_view_device_gap_audit.ps1"
    "12B" = "scripts\quality\run_stage12b_quality_view_device_data_readiness.ps1"
    "12C" = "scripts\quality\run_stage12c_annotation_device_scope_adjudication.ps1"
    "12D" = "scripts\quality\run_stage12d_annotation_cohort_readiness.ps1"
    "12D_CONSTRUCT" = "scripts\quality\run_stage12d_annotation_cohort_construction.ps1"
    "12E" = "scripts\quality\run_stage12e_partial_annotation_acceptance.ps1"
    "12F" = "scripts\quality\run_stage12f_partial_scope_evidence_freeze.ps1"
    "12G" = "scripts\quality\run_stage12g_additional_development_evidence_search.ps1"
    "12H" = "scripts\quality\run_stage12h_partial_scope_capability_freeze.ps1"
    "13A" = "scripts\multiview\run_stage13a_multiview_data_readiness.ps1"
    "13B" = "scripts\multiview\run_stage13b_study_identity_resolution.ps1"
    "13C" = "scripts\multiview\run_stage13c_patient_safe_pair_design.ps1"
    "13D" = "scripts\multiview\run_stage13d_multiview_baseline.ps1"
    "13E" = "scripts\multiview\run_stage13e_paired_validation_comparison.ps1"
    "13F" = "scripts\multiview\run_stage13f_multiview_selection_freeze.ps1"
    "13G" = "scripts\multiview\run_stage13g_locked_test_pair_readiness.ps1"
    "13H" = "scripts\multiview\run_stage13h_locked_test_evaluation_freeze.ps1"
    "13I" = "scripts\multiview\run_stage13i_one_time_locked_test_evaluation.ps1"
    "13J" = "scripts\multiview\run_stage13j_final_multiview_closure.ps1"
    "14A" = "scripts\temporal\run_stage14a_temporal_data_readiness.ps1"
    "14B" = "scripts\temporal\run_stage14b_temporal_identity_chronology_resolution.ps1"
    "15A" = "scripts\severity\run_stage15a_severity_data_readiness.ps1"
    "15B" = "scripts\severity\run_stage15b_severity_evidence_contract_resolution.ps1"
    "16A" = "scripts\reliability\run_stage16a_reliability_data_readiness.ps1"
    "16B" = "scripts\reliability\run_stage16b_reliability_contract.ps1"
    "16C" = "scripts\reliability\run_stage16c_validation_reliability_preparation.ps1"
    "16D" = "scripts\reliability\run_stage16d_validation_reliability_evaluation.ps1"
    "16E" = "scripts\reliability\run_stage16e_reliability_acceptance_decision.ps1"
    "17A" = "scripts\triage\run_stage17a_research_triage_data_readiness.ps1"
    "17B" = "scripts\triage\run_stage17b_rule_based_research_triage_contract.ps1"
    "17C" = "scripts\triage\run_stage17c_expert_priority_policy_evidence_readiness.ps1"
    "18A" = "scripts\reporting\run_stage18a_grounded_report_data_readiness.ps1"
    "18B" = "scripts\reporting\run_stage18b_deterministic_grounded_report_contract.ps1"
    "18C" = "scripts\reporting\run_stage18c_deterministic_template_implementation.ps1"
    "18D" = "scripts\reporting\run_stage18d_template_safety_validation.ps1"
    "18E" = "scripts\reporting\run_stage18e_grounded_report_acceptance_decision.ps1"
    "19A" = "scripts\verification\run_stage19a_textual_anatomical_verifier_data_readiness.ps1"
    "19B" = "scripts\verification\run_stage19b_textual_anatomical_verifier_contract.ps1"
    "19C" = "scripts\verification\run_stage19c_synthetic_verifier_implementation_validation.ps1"
    "19D" = "scripts\verification\run_stage19d_verifier_acceptance_decision.ps1"
    "20A" = "scripts\decision\run_stage20a_accept_revise_defer_data_readiness.ps1"
    "20B" = "scripts\decision\run_stage20b_deterministic_decision_contract.ps1"
    "20C" = "scripts\decision\run_stage20c_synthetic_decision_implementation_validation.ps1"
    "20D" = "scripts\decision\run_stage20d_deterministic_decision_acceptance.ps1"
    "21A" = "scripts\serving\run_stage21a_backend_gpu_worker_data_readiness.ps1"
    "21B" = "scripts\serving\run_stage21b_backend_api_worker_contract.ps1"
    "21C" = "scripts\serving\run_stage21c_synthetic_api_worker_contract_validation.ps1"
    "21D" = "scripts\serving\run_stage21d_backend_worker_implementation_readiness_decision.ps1"
    "21E" = "scripts\serving\run_stage21e_serving_dependency_implementation_protocol_freeze.ps1"
    "21F" = "scripts\serving\run_stage21f_minimal_local_backend_worker_implementation.ps1"
}
if (-not $routes.ContainsKey($Stage)) { throw "No real stage-specific launcher is registered for '$Stage'." }
$script = Join-Path $ProjectRoot $routes[$Stage]
if (-not (Test-Path -LiteralPath $script)) { throw "Registered launcher is missing: $script" }
$arguments = @{ProjectRoot=$ProjectRoot}
foreach ($name in @("PreflightOnly", "SmokeTest", "FreshStart", "Resume")) { if ((Get-Variable $name).Value) { $arguments[$name]=$true } }
& $script @arguments
exit $LASTEXITCODE
