$ErrorActionPreference='Stop'
$bundle=Get-Content artifacts/research_extensions/ext4h5/20260820T070353Z_fc35947a/review_bundle.json -Raw|ConvertFrom-Json
$review=Get-Content artifacts/research_extensions/ext4h5/completed_blinded_review.json -Raw|ConvertFrom-Json
$map=Get-Content artifacts/research_extensions/ext4h5/20260820T070353Z_fc35947a/internal_blind_map.json -Raw|ConvertFrom-Json
$mapBy=@{}; foreach($m in $map.entries){$mapBy[$m.blind_slot_id]=$m}
$out=@(); foreach($r in $review.completed_reviews){ if($r.adjudication_metadata.internal_state -ne 'RESOLVED'){continue}; $u=$bundle.review_units|? blind_slot_id -eq $r.blind_slot_id; $bad=@(); foreach($p in $u.applicability.PSObject.Properties){if($p.Value -eq 'APPLICABLE' -and $r.ratings.($p.Name) -eq 'FAIL'){$bad+=$p.Name}}; if(!$bad.Count){continue}; $flags=@($r.adjudication_metadata.flags); $mechanism=if($flags -contains 'POLARITY_CHANGE'){'state/polarity substitution'}elseif($flags -contains 'DEFER_ERROR'){'DEFER semantic object confusion'}elseif($flags -contains 'CONTRADICTION_ERROR'){'contradiction collapse'}elseif($flags -contains 'LIMITATION_EXPRESSION_ERROR'){'limitation state expression drift'}else{'unsupported proposition or semantic drift'}; $out += [ordered]@{case_id=$mapBy[$r.blind_slot_id].case_id; case_sha256=$mapBy[$r.blind_slot_id].case_sha256; slot_id=$mapBy[$r.blind_slot_id].slot_id; slot_type=$u.slot_type; model_authored_slot_text=$u.model_authored_slot_text; failed_dimensions=$bad; reviewer_flags=$flags; primary_failure_layer='LLM_SURFACE_REALIZATION_DRIFT'; failure_mechanism=$mechanism; regression_expectation='bounded architecture must reject or prevent this semantic transition'} }
if($out.Count -ne 16){throw "EXT4I_REGRESSION_COUNT:$($out.Count)"}
$obj=[ordered]@{regression_id='EXT4I_H5_RESOLVED_FAILURE_REGRESSION_V1'; purpose='architecture regression only; not model selection'; source_h4_run='20260820T070353Z_fc35947a'; source_h5_bundle_sha256='64a73ff5e7789e096ba0bbbd61966e62a22ca242f877fe26ddc887392225f0f4'; resolved_failure_count=16; unresolved_units_excluded=43; cases=@($out)}
$enc=New-Object Text.UTF8Encoding($false); [IO.File]::WriteAllText('configs/research_extensions/ext4i/ext4i_h5_resolved_failure_regression_v1.json',($obj|ConvertTo-Json -Depth 20),$enc)
